---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
script: bundle exec rake spec SPEC_OPTS='--format documentation'
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
  global:
  - PUBLISHER_LOGIN=saz
  - secure: |- 
      LL1f6eYEYmwJ3mXfnPIUjBShbhnIJu5t6dpbYPg4ePYful+EnhNncE33FXyBpMoY7V23fKUG
      TAz5WUcXX09O3ydl6TTe4IJmAl8MtLjIhHwIdPq3I+W0XQM6dDW90UPAkHVm70769iGyM/05
      9VwgKePFGdmlcV4I1hSmgJi4WMo=
matrix:
  include:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.3.0"
notifications:
  email: false
gemfile: .gemfile
